//THIS FILE HAS NO RELATION TO REDUX. THE MAIN USE IS USEREDUCER HOOK

export const passwordCreationActions = {
    SET_PASSWORD_INPUT_DIRTY: 'SET_PASSWORD_INPUT_DIRTY',
    SHOW_PASSWORD: 'SHOW_PASSWORD',
    VALIDATE_TEN_CHARACTERS: 'VALIDATE_TEN_CHARACTERS',
    VALIDATE_ONE_NUMBER: 'VALIDATE_ONE_NUMBER',
    VALIDATE_ONE_CAPITAL: 'VALIDATE_ONE_CAPITAL',
    ACCEPT_PASSWORD: 'ACCEPT_PASSWORD',
    CANCEL_PASSWORD :'CANCEL_PASSWORD',
    SHOW_RETYPED_PASSWORD: 'SHOW_RETYPED_PASSWORD',
    CONFIRM_PASSWORD_MATCH: 'CONFIRM_PASSWORD_MATCH'
};