//THIS FILE HAS NO RELATION TO REDUX. THE MAIN USE IS USE REDUCER HOOK

export default {
    GET_FIRST_NAME: "GET_FIRST_NAME",
    GET_LAST_NAME: "GET_LAST_NAME",
    GET_EMAIL: "GET_EMAIL",
    GET_EMAIL_VALIDITY: "GET_EMAIL_VALIDITY",
    GET_BIRTH_DATE: "GET_BIRTH_DATE",
    GET_COUNTRY: "GET_COUNTRY",
    GET_PHONE_NUMBER: "GET_PHONE_NUMBER",
}