//THIS FILE HAS NO RELATION TO REDUX. THE MAIN USE IS USE REDUCER HOOK

export default {
    FIRST_NAME: "FIRST_NAME",
    FIRST_NAME_VALIDITY: "FIRST_NAME_VALIDITY",
    LAST_NAME: "LAST_NAME",
    LAST_NAME_VALIDITY: "LAST_NAME_VALIDITY",
    EMAIL: "EMAIL",
    EMAIL_VALIDITY: "EMAIL_VALIDITY",
    BIRTH_DATE: "BIRTH_DATE",
    COUNTRY: "COUNTRY",
    PHONE_NUMBER: "PHONE_NUMBER",
    PHONE_NUMBER_VALIDITY: "PHONE_NUMBER_VALIDITY",
}