//THIS FILE HAS NO RELATION TO REDUX. THE MAIN USE IS USE REDUCER HOOK


export default {
    HOTELS_LOADING: 'HOTELS_LOADING',
    HOTELS_ERROR: 'HOTELS_ERROR',
    DESTINATIONS_LOADING: 'DESTINATIONS_LOADING',
    DESTINATIONS_ERROR: 'DESTINATIONS_ERROR',
    FLIGHTS_LOADING: 'FLIGHTS_LOADING',
    FLIGHTS_ERROR: 'FLIGHTS_ERROR',
    TRAINS_LOADING: 'TRAINS_LOADING',
    TRAINS_ERROR: 'TRAINS_ERROR',
    BUSES_LOADING: 'BUSES_LOADING',
    BUSES_ERROR: 'BUSES_ERROR',
    TAXIS_LOADING: 'TAXIS_LOADING',
    TAXIS_ERROR: 'TAXIS_ERROR',
    COUNTRIES_CODES_LOADING: 'COUNTRIES_CODES_LOADING',
    COUNTRIES_CODES_ERROR: 'COUNTRIES_CODES_ERROR'
}