export const RESIDENCECHOICE = ['All Inclusive', 'Half Board'] 
export const BEDCHOICE = ['1 Bed', '2 Beds']
export const GENDER = ['Male', 'Female']
export const TITLE = ['Mr.', 'Ms.']

export const HOTELS_FILTERS = ['name', 'starRating', 'streetAddress', 'locality', 'postalCode', 'countryName', 'guestReviews', 'price', 'freeCancellation', 'paymentPreference', 'noCCRequired']
export const FLIGHTS_FILTERS = ['destination', 'Airport']
export const TRAINS_FILTERS = ['type', 'name', 'description', 'distance']
export const BUSES_FILTERS = ['mode','line','direction','date','departure_time','operator_name']
export const TAXIS_FILTERS = ['Large People Carrier' , 'Executive People Carrier' , 'Luxury', 'Standar', 'People Carrier' , 'Executive']
export const FOOD_FILTERS = []