export const AUTHENTICATION = 'AUTHENTICATION';
export const LOGOUT = 'LOGOUT';

export const GET_HOTELS = 'GET_HOTELS';

export const GET_DESTINATIONS = 'GET_DESTINATIONS';

export const GET_FLIGHTS = 'GET_FLIGHTS';

export const GET_FOOD = 'GET_FOOD';

export const GET_TRAINS = 'GET_TRAINS';

export const GET_TAXIS = 'GET_TAXIS';

export const GET_BUSES = 'GET_BUSES';

export const GET_CALLING_CODES = 'GET_CALLING_CODES';

export const GET_RESERVATIONS = 'GET_RESERVATIONS';

export const VALIDATE_RESERVATION = 'VALIDATE_RESERVATION';

export const GET_FAVORITES = 'GET_FAVORITES';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAV_FAILED = 'ADD_FAV_FAILED';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const DELETE_FAV_FAILED = 'DELETE_FAV_FAILED';
export const DELETE_FAVORITES = 'DELETE_FAVORITES';
export const DELETE_FAVS_FAILED = 'DELETE_FAVS_FAILED';



