export const GET_HOTELS = 'GET_HOTELS';
export const HOTELS_LOADING = 'HOTELS_LOADING';
export const HOTELS_FAILED = 'HOTELS_FAILED';

export const GET_DESTINATIONS = 'GET_DESTINATIONS';
export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const DESTINATIONS_FAILED = 'DESTINATIONS_FAILED';

export const GET_FLIGHTS = 'GET_FLIGHTS';
export const FLIGHTS_LOADING = 'FLIGHTS_LOADING';
export const FLIGHTS_FAILED = 'FLIGHTS_FAILED';

export const GET_FOOD = 'GET_FOOD';
export const FOOD_LOADING = 'FOOD_LOADING';
export const FOOD_FAILED = 'FOOD_FAILED';

export const GET_TRAINS = 'GET_TRAINS';
export const TRAINS_LOADING = 'TRAINS_LOADING';
export const TRAINS_FAILED = 'TRAINS_FAILED';

export const GET_TAXIS = 'GET_TAXIS';
export const TAXIS_LOADING = 'TAXIS_LOADING';
export const TAXIS_FAILED = 'TAXIS_FAILED';

export const GET_BUSES = 'GET_BUSES';
export const BUSES_LOADING = 'BUSES_LOADING';
export const BUSES_FAILED = 'BUSES_FAILED';

export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const RESERVATIONS_LOADING = 'RESERVATIONS_LOADING';
export const RESERVATIONS_FAILED = 'RESERVATIONS_FAILED';

export const VALIDATE_RESERVATION = 'VALIDATE_RESERVATION';
export const RESERVATION_LOADING = 'RESERVATION_LOADING';
export const RESERVATION_FAILED = 'RESERVATION_FAILED';

export const GET_FAVORITES = 'GET_FAVORITES';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAV_FAILED = 'ADD_FAV_FAILED';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const DELETE_FAV_FAILED = 'DELETE_FAV_FAILED';
export const DELETE_FAVORITES = 'DELETE_FAVORITES';
export const DELETE_FAVS_FAILED = 'DELETE_FAVS_FAILED';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const COUNTRIES_FAILED = 'COUNTRIES_FAILED';


